# Generated by Django 5.1.6 on 2026-04-14 20:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del cliente')),
                ('key_prefix', models.CharField(max_length=8, verbose_name='Prefijo (identificacion)')),
                ('key_hash', models.CharField(max_length=64, unique=True, verbose_name='Hash de la key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'api_keys',
            },
        ),
        migrations.CreateModel(
            name='CorreoAutorizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electronico')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre/Descripcion')),
                ('es_buzon_principal', models.BooleanField(default=False, help_text='Si es True, se usara como buzon para enviar busquedas', verbose_name='Es Buzon Principal')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),  # NOSONAR
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
            ],
            options={
                'verbose_name': 'Correo Autorizado',
                'verbose_name_plural': 'Correos Autorizados',
                'db_table': 'correos_autorizados',
                'ordering': ['-es_buzon_principal', 'email'],
            },
        ),
        migrations.CreateModel(
            name='CorreoProcesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='ID del Email en Graph')),
                ('buzon', models.CharField(max_length=255, verbose_name='Buzon de Origen')),
                ('subject', models.CharField(blank=True, max_length=500, null=True, verbose_name='Asunto')),
                ('fecha_email', models.DateTimeField(blank=True, null=True, verbose_name='Fecha del Email')),
                ('procesado_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Procesamiento')),
            ],
            options={
                'verbose_name': 'Correo Procesado',
                'verbose_name_plural': 'Correos Procesados',
                'db_table': 'correos_procesados',
                'ordering': ['-procesado_at'],
            },
        ),
        migrations.CreateModel(
            name='LogConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SUPPLOS', 'Consulta Supplos'), ('GRAPH', 'Consulta Graph'), ('CONSOLIDACION', 'Consolidacion')], max_length=20, verbose_name='Tipo de Consulta')),
                ('parametros', models.JSONField(verbose_name='Parametros de Consulta')),
                ('respuesta_exitosa', models.BooleanField(default=False, verbose_name='Respuesta Exitosa')),
                ('mensaje_error', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('tiempo_respuesta_ms', models.PositiveIntegerField(default=0, verbose_name='Tiempo de Respuesta (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),  # NOSONAR
            ],
            options={
                'verbose_name': 'Log de Consulta',
                'verbose_name_plural': 'Logs de Consultas',
                'db_table': 'log_consultas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_centro_suministrador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Proveedor/Centro Suministrador')),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razon Social')),
                ('comprador', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comprador')),
                ('organizacion_compras', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organizacion de Compras')),
                ('planta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Planta')),
                ('documento_compras', models.CharField(db_index=True, max_length=50, verbose_name='Documento de Compras / Numero de Pedido')),
                ('posicion', models.CharField(blank=True, max_length=20, null=True, verbose_name='Posicion')),
                ('material', models.CharField(blank=True, max_length=100, null=True, verbose_name='Material')),
                ('texto_breve', models.TextField(blank=True, null=True, verbose_name='Texto Breve / Descripcion')),
                ('cantidad_pedido', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cantidad Pedido')),
                ('por_entregar', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Por Entregar')),
                ('precio_neto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Precio Neto')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('fecha_programada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Programada')),
                ('estado_pedido', models.CharField(choices=[('Vigente', 'Vigente'), ('Entregado', 'Entregado'), ('Parcial', 'Entrega Parcial'), ('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado'), ('En Transito', 'En Transito')], default='Vigente', max_length=30, verbose_name='Estado del Pedido')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones (Proveedor)')),
                ('estado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado Interno')),
                ('observaciones_corona', models.TextField(blank=True, null=True, verbose_name='Observaciones Corona')),
                ('fuente_supplos', models.BooleanField(default=False, verbose_name='Datos de Supplos')),
                ('fuente_graph', models.BooleanField(default=False, verbose_name='Datos de Graph/Email')),
                ('ultima_sincronizacion', models.DateTimeField(auto_now=True, verbose_name='Ultima Sincronizacion')),
                ('datos_raw_supplos', models.JSONField(blank=True, null=True, verbose_name='Datos crudos Supplos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),  # NOSONAR
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuplosToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(verbose_name='Token de Acceso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),  # NOSONAR
                ('expires_at', models.DateTimeField(verbose_name='Fecha de Expiracion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Token Supplos',
                'verbose_name_plural': 'Tokens Supplos',
                'db_table': 'supplos_tokens',
            },
        ),
        migrations.CreateModel(
            name='TrazabilidadPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fuente', models.CharField(choices=[('SUPPLOS', 'Supplos'), ('GRAPH', 'Graph/Email'), ('MANUAL', 'Manual')], max_length=20, verbose_name='Fuente de Datos')),
                ('estado_anterior', models.CharField(blank=True, max_length=30, null=True, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Estado Nuevo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('observaciones_proveedor', models.TextField(blank=True, null=True, verbose_name='Observaciones del Proveedor')),
                ('email_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID del Email')),
                ('email_subject', models.CharField(blank=True, max_length=500, null=True, verbose_name='Asunto del Email')),
                ('email_from', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remitente del Email')),
                ('email_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha del Email')),
                ('datos_raw', models.JSONField(blank=True, null=True, verbose_name='Datos Crudos')),
            ],
            options={
                'verbose_name': 'Trazabilidad de Pedido',
                'verbose_name_plural': 'Trazabilidad de Pedidos',
                'db_table': 'trazabilidad_pedidos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
