# Generated by Django 5.1.6 on 2026-04-14 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integraciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logconsulta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_integracion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['documento_compras'], name='pedidos_documen_88d4a9_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado_pedido'], name='pedidos_estado__75d753_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['fecha_entrega'], name='pedidos_fecha_e_167ca2_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['razon_social'], name='pedidos_razon_s_e1c9da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pedido',
            unique_together={('documento_compras', 'posicion')},
        ),
        migrations.AddField(
            model_name='correoprocesado',
            name='pedidos_relacionados',
            field=models.ManyToManyField(blank=True, related_name='correos_procesados', to='integraciones.pedido', verbose_name='Pedidos Relacionados'),
        ),
        migrations.AddField(
            model_name='trazabilidadpedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trazabilidad', to='integraciones.pedido', verbose_name='Pedido'),
        ),
    ]
