# Generated by Django 5.1.6 on 2026-04-14 20:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Usuario')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre completo')),
                ('phone', models.CharField(max_length=100, verbose_name='Teléfono')),
                ('identification', models.CharField(max_length=100, verbose_name='Identificación')),
                ('born_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('image', models.ImageField(blank=True, default='media/user/profile.jpeg', null=True, upload_to='media/user/', verbose_name='Imagen de usuario')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrador')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último inicio de sesión')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='auth.group', verbose_name='Rol')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
