# Generated by Django 5.1.6 on 2026-04-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='user/profile.jpeg', null=True, upload_to='user/', verbose_name='Imagen de usuario'),
        ),
    ]
