# Generated by Django 5.1.6 on 2026-04-16 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del lote')),
                ('variedad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Variedad')),
                ('año_siembra', models.CharField(blank=True, max_length=50, null=True, verbose_name='Año siembra / zoca')),
                ('proxima_renovacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Próxima renovación')),
                ('num_arboles', models.IntegerField(default=0, verbose_name='Número de árboles')),
                ('gramos_abono_palo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Gramos abono / palo')),
                ('bultos_produccion', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Bultos producción')),
                ('bultos_urea', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Bultos urea')),
                ('bultos_dap', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Bultos DAP')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'db_table': 'lotes',
            },
        ),
        migrations.CreateModel(
            name='Floracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('calidad', models.CharField(choices=[('buena', 'Buena'), ('regular', 'Regular'), ('muy_buena', 'Muy buena'), ('excelente', 'Excelente')], max_length=20, verbose_name='Calidad de floración')),
                ('abonada_ideal', models.BooleanField(blank=True, null=True, verbose_name='Abonada ideal')),
                ('broca_ideal', models.BooleanField(blank=True, null=True, verbose_name='Broca ideal')),
                ('roya_ideal', models.BooleanField(blank=True, null=True, verbose_name='Roya ideal')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floraciones', to='produccion.lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Floración',
                'verbose_name_plural': 'Floraciones',
                'db_table': 'floraciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MezclaAbono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('formula', models.CharField(max_length=300, verbose_name='Fórmula')),
                ('num_arboles', models.IntegerField(blank=True, null=True, verbose_name='Número de árboles')),
                ('gramos_por_arbol', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Gramos por árbol')),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo total')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mezclas_abono', to='produccion.lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Mezcla de Abono',
                'verbose_name_plural': 'Mezclas de Abono',
                'db_table': 'mezclas_abono',
            },
        ),
        migrations.CreateModel(
            name='MezclaAbonoFertilizante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('fertilizante', models.CharField(max_length=100, verbose_name='Fertilizante')),
                ('num_bultos', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Número de bultos')),
                ('precio_bulto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio x bulto')),
                ('mezcla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizantes', to='produccion.mezclaabono', verbose_name='Mezcla')),
            ],
            options={
                'verbose_name': 'Fertilizante en mezcla',
                'verbose_name_plural': 'Fertilizantes en mezcla',
                'db_table': 'mezclas_abono_fertilizantes',
            },
        ),
        migrations.CreateModel(
            name='VentaBanano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('tipo_platano', models.CharField(choices=[('banano_extra', 'Banano Extra'), ('banano_primera', 'Banano Primera'), ('banano_segunda', 'Banano Segunda'), ('platano_extra', 'Plátano Extra x dedo'), ('platano_segunda', 'Plátano Segunda x dedo')], db_index=True, max_length=30, verbose_name='Tipo')),
                ('kilos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kilos')),
                ('precio_kilo', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio x kilo')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor total')),
                ('facturado_a', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facturado a')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_banano', to='finanzas.cuenta', verbose_name='Cuenta destino')),
            ],
            options={
                'verbose_name': 'Venta de Banano',
                'verbose_name_plural': 'Ventas de Banano',
                'db_table': 'ventas_banano',
            },
        ),
        migrations.CreateModel(
            name='VentaCafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('kilos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kilos')),
                ('cargas', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Cargas')),
                ('tipo_cafe', models.CharField(choices=[('pergamino_seco', 'Pergamino Seco'), ('pasilla', 'Pasilla'), ('corriente', 'Corriente'), ('cereza', 'Cereza'), ('verde', 'Verde')], db_index=True, max_length=20, verbose_name='Tipo de café')),
                ('factor', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Factor')),
                ('precio_kilo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio x kilo')),
                ('precio_carga', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio x carga')),
                ('comprador', models.CharField(max_length=100, verbose_name='Comprador')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor total')),
                ('deduccion', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Deducción')),
                ('retefuente', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Retefuente')),
                ('valor_neto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor neto')),
                ('facturado_a', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facturado a')),
                ('conversion_cereza_seco', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Conversión cereza/seco')),
                ('beneficio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Beneficio')),
                ('transportador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transportador')),
                ('valor_transporte', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor transporte')),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_cafe', to='finanzas.cuenta', verbose_name='Cuenta destino')),
            ],
            options={
                'verbose_name': 'Venta de Café',
                'verbose_name_plural': 'Ventas de Café',
                'db_table': 'ventas_cafe',
            },
        ),
        migrations.CreateModel(
            name='VentaCafeTostado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_venta', models.DateField(db_index=True, verbose_name='Fecha venta')),
                ('cliente', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cliente')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad (unidades)')),
                ('presentacion', models.CharField(choices=[('250g', '250 gramos'), ('500g', '500 gramos'), ('2500g', '2.5 kg')], max_length=10, verbose_name='Presentación')),
                ('tipo_cafe', models.CharField(choices=[('molido', 'Molido'), ('grano', 'Grano')], max_length=10, verbose_name='Molido o Grano')),
                ('seleccionado', models.BooleanField(default=False, verbose_name='Seleccionado')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha pago')),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_cafe_tostado', to='finanzas.cuenta', verbose_name='Cuenta destino')),
            ],
            options={
                'verbose_name': 'Venta Café Tostado',
                'verbose_name_plural': 'Ventas Café Tostado',
                'db_table': 'ventas_cafe_tostado',
            },
        ),
    ]
