# Generated by Django 5.1.6 on 2026-04-16 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cédula')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('labor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Labor principal')),
                ('jornal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Jornal diario')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('salario_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salario mensual')),
                ('salario_semanal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salario semanal')),
                ('eps', models.CharField(blank=True, max_length=100, null=True, verbose_name='EPS')),
                ('pension', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pensión')),
                ('arl', models.CharField(blank=True, max_length=100, null=True, verbose_name='ARL')),
                ('caja_compensacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Caja de compensación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='PrestamoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha préstamo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('concepto', models.CharField(max_length=300, verbose_name='Concepto')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo pendiente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='nomina.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Préstamo a empleado',
                'verbose_name_plural': 'Préstamos a empleados',
                'db_table': 'prestamos_empleados',
            },
        ),
        migrations.CreateModel(
            name='AbonoPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha', models.DateField(verbose_name='Fecha abono')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('nota', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nota')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='nomina.prestamoempleado', verbose_name='Préstamo')),
            ],
            options={
                'verbose_name': 'Abono a préstamo',
                'verbose_name_plural': 'Abonos a préstamos',
                'db_table': 'abonos_prestamos',
            },
        ),
        migrations.CreateModel(
            name='ControlSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_inicio', models.DateField(db_index=True, verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin')),
                ('tipo_labor', models.CharField(choices=[('recoleccion', 'Recolección'), ('guadana', 'Guadaña'), ('abono', 'Abono'), ('varios', 'Varios'), ('banano', 'Banano'), ('cosecha', 'Cosecha'), ('siembra', 'Siembra'), ('embolsada', 'Embolsada'), ('auxilio_labor', 'Auxilio Labor'), ('auxilio_transporte', 'Auxilio Transporte'), ('permiso', 'Permiso'), ('nomina', 'Nómina'), ('contrato', 'Contrato')], db_index=True, max_length=30, verbose_name='Tipo labor')),
                ('tipo_cobro', models.CharField(choices=[('kilos', 'Kilos'), ('jornal', 'Jornal'), ('contrato', 'Contrato'), ('nomina', 'Nómina')], max_length=20, verbose_name='Tipo cobro')),
                ('lote', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lote')),
                ('kilos', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Kilos')),
                ('jornales', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Jornales')),
                ('costo_unidad', models.DecimalField(decimal_places=5, max_digits=12, verbose_name='Costo x kilo / jornal')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor total')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('es_vale', models.BooleanField(default=False, help_text='True = registrado en planilla de vales, False = planilla formal', verbose_name='Es vale')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_control', to='nomina.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Control Semanal',
                'verbose_name_plural': 'Control Semanal',
                'db_table': 'control_semanal',
                'indexes': [models.Index(fields=['empleado', 'fecha_inicio'], name='control_sem_emplead_dea4ed_idx'), models.Index(fields=['fecha_inicio', 'tipo_labor'], name='control_sem_fecha_i_133db8_idx')],
            },
        ),
    ]
