# Generated by Django 5.1.6 on 2026-04-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0006_rename_control_sem_fecha_i_133db8_idx_control_sem_fecha_i_f7e4e5_idx_and_more'),
        ('nomina', '0006_tipos_labor_nuevos_excel'),
    ]

    operations = [
    ]
