# Generated by Django 5.1.6 on 2026-04-16 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('bancaria', 'Bancaria'), ('efectivo', 'Efectivo'), ('prestamo', 'Préstamo'), ('agencia', 'Agencia / Cooperativa'), ('dividendos', 'Dividendos'), ('vale', 'Vale')], max_length=20, verbose_name='Tipo')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo inicial')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'db_table': 'cuentas',
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('observacion', models.TextField(verbose_name='Observación')),
            ],
            options={
                'verbose_name': 'Observación',
                'verbose_name_plural': 'Observaciones',
                'db_table': 'observaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('cedula_nit', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cédula / NIT')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('origen', models.CharField(blank=True, max_length=200, null=True, verbose_name='Origen')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='finanzas.cuenta', verbose_name='Cuenta destino')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'db_table': 'ingresos',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='finanzas.cuenta', verbose_name='Cuenta destino')),
                ('cuenta_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='finanzas.cuenta', verbose_name='Cuenta origen')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'db_table': 'transacciones',
            },
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre / Concepto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Cantidad')),
                ('unidad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('categoria', models.CharField(choices=[('fertilizantes', 'Fertilizantes'), ('herbicidas', 'Herbicidas'), ('nomina', 'Nómina'), ('seguridad_social', 'Seguridad Social'), ('transporte', 'Transporte'), ('viaticos', 'Viáticos'), ('acueducto', 'Acueducto'), ('epm', 'EPM'), ('comsab', 'Comsab'), ('mantenimientos', 'Mantenimientos'), ('varios', 'Varios'), ('beneficio', 'Beneficio'), ('guadana', 'Guadaña'), ('construcciones', 'Construcciones'), ('impuestos', 'Impuestos'), ('animales', 'Animales'), ('siembra', 'Siembra'), ('herramientas', 'Herramientas'), ('broca', 'Broca'), ('roya', 'Roya'), ('moto', 'Moto'), ('prestamo_empleados', 'Préstamo empleados'), ('no_aplica', 'No aplica'), ('activos_fijos', 'Activos fijos'), ('banano', 'Banano'), ('compra_finca', 'Compra Finca'), ('capacitaciones', 'Capacitaciones')], db_index=True, max_length=50, verbose_name='Categoría')),
                ('nit_proveedor_destino', models.CharField(blank=True, max_length=30, null=True, verbose_name='NIT / Destino')),
                ('facturado_a', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facturado a')),
                ('abono_deuda', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Abono a deuda')),
                ('restante', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Restante')),
                ('estado', models.CharField(choices=[('pagada', 'Pagada'), ('pendiente', 'Pendiente'), ('parcial', 'Parcial')], default='pagada', max_length=20, verbose_name='Estado')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egresos', to='finanzas.cuenta', verbose_name='Cuenta')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos', to='finanzas.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
                'db_table': 'egresos',
                'indexes': [models.Index(fields=['fecha', 'categoria'], name='egresos_fecha_e89304_idx')],
            },
        ),
    ]
